sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: d0+FeV6KqVAzyRRuN0576pZIz1IfBUoz8Z898a3IEbrDDNoqP8r8lDxnZxsN2yGyo6oULMyKZcconSEOiazfnFasmf6jwSP07PB9VLZFVNZQ+WRXsbkM9CBwI4o/f42BGmJ+nnQE8T5/O1MYwo3xoo6zzpHvx2Gsln7ALr51w0nClxUx9bjyt5BwYzcFY/aetuGuhtxioZfauB7k1yzrGbRKc8BsvORqKjmNP5RrOvcDMyzFJN+Fr/NZaOQ0/Mp8qnECtVfXiduUdjr4xybdxlbIZ7e/UlwaXknB1NHGXzZgFgL0E5hlXd/glI7GTwVBIVEkhyOv/4edQZo903TeKWdOpN/dbO4AUaMMgRDA5wjNu0R5RU3at+W+JyeSW0xcu7w8t1X1cAnFcZNR//TK72uPxmN+CTseKG09ulDStMvisiq/xwIpOBbubSwbMW6KSXa9NBDHPNul6yTj7FTeg3LSJ43HigMPYbClPWYgyE4NsYZjHCT80MNsjU3JKnCJowmYjY4jiRibNj0pkVwfQJPMSTEN5ScmjG6ZM8MDOVtKaOH5t6rHm0fNiMd/6ANo88/CQ5mSrPkrSqjMHdRzrvoSchxdagjKI/TNlLQKjyuqNVaglghZJueM+36Wxq0exzstpm34MZ2bQqV1uxKaGrdBw3XGJZkxmgg3Q8drCZM=
    - secure: N9rF69iTyanFVHPOSYET4av74P12nGddAnqwrYlyb/ct/rYiqD/uyeIDpvW9dWacxeUFelwArbtOiooI/8Bu2BcKo2M5ka8ZQ2FJKzJyCZy1jWX6sZEolRadzmBdVF6L/RDPLRgI31+96j7pJb/2j4Xis0gMrJMxvEIl2tkOQQmg1BxWKMhL7KbG2UNOQXxBrGIqbQguyYnjmAbqi3jtoRPOtrhv/4F+RqrGq8zqHxAJI48vHhmo6zbdwhhh2gskD6LUdP9ikSivXk9sNMF/jgrxp5GO+8L3NoMr6VkpxSHHIih/Ec4JNEvG7zMgk3xWYNIRdFrR3E1jv/k2BtatVMCvMXU3puNFd0jZ5gCJr076+n2KCHOse7jGQ9JFHsKePmRnW7YsaMtM+7KyprX8iitHcNsSbwj6N1wHOJjlsSZjy3PrVkUZwkXLrR6spBYinMEXSpy+CXMht2fXes5UbXnyzTrsI6xuOaUPjUoLOMxf3UQsYWsF+uJ2x0z4cV0XN8Ilfab4Rr2umMABUYZV4XHwEYgDk6Qh1t7zilaMNgC8bMjECQiwDM7AfEOJ+eQ1twvBb1/KZyWr56l++N006KztHlXcsA1ZeSUaDdEdvgzzm5pdtL1tXS6Uady3DzFlhCDMuDLe2pi/Vo9/B3KN44p/w63KcWmqOERp9SwcEto=
